import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Navigation from '@/app/components/Navigation';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Test App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation />
        <main className="container mx-auto mt-6 px-2">{children}</main>
      </body>
    </html>
  );
}
